labels:
  'fix':
    include:
      - '\bfix\b'
  'documentation':
    include:
      - '\bdocs\b'
  'test':
    include:
      - '\btest\b'
  'feature':
    include:
      - '\bfeat\b'
  'bug':
    include:
      - '\bbug\b'
  'refactor':
    include:
      - '\brefactor\b'
  'chore':
    include:
      - '\bchore\b'
